//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyToUseGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyToUseGenerator.Resources.UserInterface", typeof(UserInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any character which can be typed.
        /// </summary>
        public static string AnyCharacterWhichCanBeTypedRadioButtonText {
            get {
                return ResourceManager.GetString("AnyCharacterWhichCanBeTypedRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any upper-case letter, lower-case letter, number or symbol character can appear in the password.  Spaces cannot appear in the password..
        /// </summary>
        public static string AnyCharacterWhichCanBeTypedRadioButtonToolTipText {
            get {
                return ResourceManager.GetString("AnyCharacterWhichCanBeTypedRadioButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+F4.
        /// </summary>
        public static string CloseWindowButtonUIAutomationAcceleratorKey {
            get {
                return ResourceManager.GetString("CloseWindowButtonUIAutomationAcceleratorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseWindowButtonUIAutomationName {
            get {
                return ResourceManager.GetString("CloseWindowButtonUIAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy to Clipboard.
        /// </summary>
        public static string CopyToClipboardButtonText {
            get {
                return ResourceManager.GetString("CopyToClipboardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_reate New Password.
        /// </summary>
        public static string CreateNewPasswordButtonText {
            get {
                return ResourceManager.GetString("CreateNewPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        public static string CreateNewPasswordWindowTitle {
            get {
                return ResourceManager.GetString("CreateNewPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create Password.
        /// </summary>
        public static string CreatePasswordButtonText {
            get {
                return ResourceManager.GetString("CreatePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string DocumentationButtonText {
            get {
                return ResourceManager.GetString("DocumentationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Release.
        /// </summary>
        public static string DownloadReleaseButtonText {
            get {
                return ResourceManager.GetString("DownloadReleaseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator {0}.{1}.{2}.
        /// </summary>
        public static string GeneratorNameAndVersionFormatString {
            get {
                return ResourceManager.GetString("GeneratorNameAndVersionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpButtonText {
            get {
                return ResourceManager.GetString("HelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Help.
        /// </summary>
        public static string HelpWindowTitle {
            get {
                return ResourceManager.GetString("HelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters and numbers.
        /// </summary>
        public static string LettersAndNumbersRadioButtonText {
            get {
                return ResourceManager.GetString("LettersAndNumbersRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any upper-case letter, lower-case letter or number can appear in the password.
        /// </summary>
        public static string LettersAndNumbersRadioButtonToolTipText {
            get {
                return ResourceManager.GetString("LettersAndNumbersRadioButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeWindowButtonUIAutomationName {
            get {
                return ResourceManager.GetString("MinimizeWindowButtonUIAutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The newly created password may contain lower-case and upper-case characters.  Your screen reader may not distinguish between character case by default.  Please configure it to do so if you want to copy down the password.  Also, your password contains symbols (characters which are not letters or numbers) and your screen reader may not read the symbols by default.  Please configure it to read the symbols if you want to hear the entire password.  Note that character case is important because it makes passwords [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewlyCreatedAllCharacterPasswordHelpText {
            get {
                return ResourceManager.GetString("NewlyCreatedAllCharacterPasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The newly created password may contain lower-case and upper-case characters.  Your screen reader may not distinguish between character case by default.  Please configure it to do so if you want to copy down the password.  Note using lower-case and upper-case characters in a password makes the password much more secure.  .
        /// </summary>
        public static string NewlyCreatedAlphaNumericPasswordHelpText {
            get {
                return ResourceManager.GetString("NewlyCreatedAlphaNumericPasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly Created Password.
        /// </summary>
        public static string NewlyCreatedPasswordLabel {
            get {
                return ResourceManager.GetString("NewlyCreatedPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters which may be included in the new password.
        /// </summary>
        public static string NewPasswordCharacterSetLabel {
            get {
                return ResourceManager.GetString("NewPasswordCharacterSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Length.
        /// </summary>
        public static string NewPasswordLengthLabel {
            get {
                return ResourceManager.GetString("NewPasswordLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string NumbersRadioButtonText {
            get {
                return ResourceManager.GetString("NumbersRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any number can appear in the password.  These passwords are usually used for 4 to 6 number passwords called Personal Identification Numbers (PINs)..
        /// </summary>
        public static string NumbersRadioButtonToolTipText {
            get {
                return ResourceManager.GetString("NumbersRadioButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Advice.
        /// </summary>
        public static string PasswordAdviceButtonText {
            get {
                return ResourceManager.GetString("PasswordAdviceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength Description.
        /// </summary>
        public static string PasswordStrengthDescriptionLabel {
            get {
                return ResourceManager.GetString("PasswordStrengthDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength.
        /// </summary>
        public static string PasswordStrengthLabel {
            get {
                return ResourceManager.GetString("PasswordStrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website.
        /// </summary>
        public static string ProjectWebSiteButtonText {
            get {
                return ResourceManager.GetString("ProjectWebSiteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Problems or Give Feedback.
        /// </summary>
        public static string ReportProblemsButtonText {
            get {
                return ResourceManager.GetString("ReportProblemsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update default password length and type.
        /// </summary>
        public static string UpdateDefaultPasswordLengthAndTypeCheckBoxText {
            get {
                return ResourceManager.GetString("UpdateDefaultPasswordLengthAndTypeCheckBoxText", resourceCulture);
            }
        }
    }
}
