//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericCommandLineArgumentParser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenericCommandLineArgumentParser.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user did not specify a valid command parameter because the command parameter did not start with a / character.  A command parameter is the first parameter passed to the program (i.e. the parameter which comes right after the program&apos;s name on the command line).  Here is the invalid command parameter: {0}.
        /// </summary>
        internal static string CommandParameterMissingBackSlashPrefix {
            get {
                return ResourceManager.GetString("CommandParameterMissingBackSlashPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID COMMAND LINE ARGUMENT: {0}.
        /// </summary>
        internal static string ICLAExceptionMessageFormatString {
            get {
                return ResourceManager.GetString("ICLAExceptionMessageFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command parameter is not valid because it does not correspond to a valid command.  Here is the invalid command parameter: {0} .
        /// </summary>
        internal static string InvalidCommandParameterSpecified {
            get {
                return ResourceManager.GetString("InvalidCommandParameterSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user passed {0} command line parameters to the program but the specified command only has between {1} and {2} command line parameters (this count includes the command parameter)..
        /// </summary>
        internal static string InvalidNumberOfCommandLineArgumentsForAParticularCommand {
            get {
                return ResourceManager.GetString("InvalidNumberOfCommandLineArgumentsForAParticularCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user did not specify any command line arguments..
        /// </summary>
        internal static string NoCommandLineArgumentsSpecified {
            get {
                return ResourceManager.GetString("NoCommandLineArgumentsSpecified", resourceCulture);
            }
        }
    }
}
