name: Main Check-in Verification Workflow

# For more information on permissions, please see the following references:
# - https://docs.github.com/en/actions/reference/authentication-in-a-workflow 
# - https://docs.github.com/en/rest/reference/permissions-required-for-github-apps
# 
permissions: 
  contents: read
  pull-requests: read

on:
  push:
    branches: 
      - main

  pull_request:
    branches:
      - main
    
    # Here is some documentation which explains what the pull request synchronize event is: https://github.community/t/what-is-a-pull-request-synchronize-event/14784/3
    types: 
      - opened
      - edited
      - reopened
      - synchronize
      - closed

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Get the changed source code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
